name: Discord Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  sending:
    runs-on: ubuntu-latest
    steps:
    - name: Discord notification
      uses: LeGitHubDeTai/github-to-discord@main
      env:
        DISCORD_WEBHOOK:  ${{ secrets.WEBHOOK_URL_BAMBU }}
        DISCORD_USERNAME: Release Announcement
        MESSAGE_TITLE: New Release!
        MESSAGE_DESCRIPTION: Bambu HomeAssistant Flows
        MESSAGE_URL: https://github.com/WolfwithSword/Bambu-HomeAssistant-Flows/releases/latest
        CONTENT: null;
        SECTION_NAME: "Changelog"
        AUTHOR_NAME: "Wolfwithsword"
        FOOTER_TEXT: "- WwS"
        IMAGE: null;
