name: GitHub Actions Zip Media
on:
 workflow_dispatch:
 push:
   branches:
     - main
     - master
     - test
jobs:
  To-Zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - uses: actions/upload-artifact@v4
        with:
          name: media
          path: /home/runner/work/Bambu-HomeAssistant-Flows/Bambu-HomeAssistant-Flows/files/media/
          if-no-files-found: error 
