name: GitHub Actions Zip Media
on:
 workflow_dispatch:
 schedule:
  - cron: "30 1 1,15 * *"
 push:
   paths:
     - '.github/workflows/**'
     - 'files/media/**'
   branches:
     - main
jobs:
  To-Zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: bambu-ha-media-files
          path: /home/runner/work/Bambu-HomeAssistant-Flows/Bambu-HomeAssistant-Flows/files/media/
          if-no-files-found: error 
          retention-days: 20
      - name: Zip for Nightly
        run: | 
          zip -r bambu-ha-media-files.zip  /home/runner/work/Bambu-HomeAssistant-Flows/Bambu-HomeAssistant-Flows/files/media/*
      - name: Release nightly
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.BHAF_GITHUB_TOKEN }}
          prerelease: true
          name: nightly
          tag_name: nightly
          files: bambu-ha-media-files.zip
          fail_on_unmatched_files: true
          
          